project:
  type: website

website:
  title: "my_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - article.qmd
      - about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly

    css: styles.css
    toc: true



